# Generated by Django 4.2.4 on 2023-08-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_student_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="file",
        ),
    ]
