# Generated by Django 4.2.4 on 2023-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_student_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("speed", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="product",
        ),
    ]
